---
- include_tasks: versioncheck.yml
  when: submodules_versioncheck|bool

- name: disable sleep.target
  become: true
  systemd:
    name: sleep.target
    masked: yes
  when: mask_sleep_target | bool

- name: allow sleep.target
  become: true
  systemd:
    name: sleep.target
    masked: no
  when: not mask_sleep_target | bool

- name: disable suspend.target
  become: true
  systemd:
    name: suspend.target
    masked: yes
  when: mask_suspend_target | bool

- name: allow suspend.target
  become: true
  systemd:
    name: suspend.target
    masked: no
  when: not mask_suspend_target | bool

- name: disable hibernate.target
  become: true
  systemd:
    name: hibernate.target
    masked: yes
  when: mask_hibernate_target | bool

- name: allow hibernate.target
  become: true
  systemd:
    name: hibernate.target
    masked: no
  when: not mask_hibernate_target | bool

- name: disable hybrid-sleep.target
  become: true
  systemd:
    name: hybrid-sleep.target
    masked: yes
  when: mask_hybrid_sleep_target | bool

- name: allow hybrid-sleep.target
  become: true
  systemd:
    name: hybrid-sleep.target
    masked: no
  when: not mask_hybrid_sleep_target | bool

- name: temporarily disable screensaver
  become: true
  command: "xset s off"
  when: temporarily_disable_screensaver | bool
  changed_when: false
  failed_when: false

- name: temporarily disable screensaver
  become: true
  command: "xset -dpms"
  when: temporarily_disable_screensaver | bool
  changed_when: false
  failed_when: false
